sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t psharp760/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true psharp760/react-test npm test

after_success:
  - docker build -t psharp760/multi-client ./client
  - docker build -t psharp760/mulit-nginx ./nginx
  - docker build -t psharp760/multi-server ./server
  - docker build -t psharp760/multi-worker ./worker
  # login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push psharp760/multi-client
  - docker push psharp760/multi-nginx
  - docker push psharp760/multi-server
  - docker push psharp760/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-735165036301'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
